/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaprestamos;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author erikr
 */
public class ReversarCobros extends javax.swing.JFrame {

    /**
     * Creates new form ReversarCobros
     */
    public ReversarCobros() {
        initComponents();
        // Obtener el tamaño de la pantalla
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension pantalla = toolkit.getScreenSize();

        // Obtener el tamaño de la ventana
        Dimension ventanaSize = getSize();

        // Calcular la posición para centrar la ventana
        int x = (pantalla.width - ventanaSize.width) / 2;
        int y = (pantalla.height - ventanaSize.height) / 2;

        // Establecer la posición de la ventana
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnioFinal = new javax.swing.JTextField();
        btnReversarCobros = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDiaInicio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMesInicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnioInicio = new javax.swing.JTextField();
        txtDiaFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMesFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("FECHA INICIO");

        jLabel7.setText("/");

        jLabel3.setText("FECHA FIN");

        btnReversarCobros.setText("REVERSAR COBROS");
        btnReversarCobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReversarCobrosActionPerformed(evt);
            }
        });

        jLabel8.setText("DIA");

        jLabel9.setText("MES");

        jLabel4.setText("/");

        jLabel10.setText("AÑO");

        jLabel5.setText("/");

        jLabel6.setText("/");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("REVERSAR COBROS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAnioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel9)
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel10))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnReversarCobros)
                            .addGap(28, 28, 28))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addGap(35, 35, 35)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtAnioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReversarCobros)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReversarCobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReversarCobrosActionPerformed
        // TODO add your handling code here:
        // Obtener las fechas desde los campos de texto
        String fechaInicioStr = txtDiaInicio.getText() + "/" + txtMesInicio.getText() + "/" + txtAnioInicio.getText();
        String fechaFinStr = txtDiaFinal.getText() + "/" + txtMesFinal.getText() + "/" + txtAnioFinal.getText();

        // Convertir las fechas de String a Date
        Date fechaInicio = parsearFecha(fechaInicioStr);
        Date fechaFin = parsearFecha(fechaFinStr);

        if (fechaInicio == null || fechaFin == null) {
            JOptionPane.showMessageDialog(null, "Fechas inválidas. Por favor, ingrese fechas válidas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método de reversión de cobros
        int totalPagosRevertidos = reversarCobros(fechaInicio, fechaFin);

        // Mostrar un mensaje con la cantidad total de pagos revertidos
        JOptionPane.showMessageDialog(null, "Cobros revertidos exitosamente.\nCantidad total de pagos revertidos: " + totalPagosRevertidos, "Éxito", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnReversarCobrosActionPerformed

    public static Date parsearFecha(String fechaStr) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            return sdf.parse(fechaStr);
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static int reversarCobros(Date fechaInicio, Date fechaFin) {
        List<String> cobrosRevertidos = new ArrayList<>();
        File archivoOriginal = new File("Cuota_Prestamo.txt");
        File archivoTemporal = new File("Cuota_Prestamo.tmp");
        int pagosRevertidos = 0; // Contador para los pagos revertidos

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try (BufferedReader br = new BufferedReader(new FileReader(archivoOriginal)); BufferedWriter bw = new BufferedWriter(new FileWriter(archivoTemporal))) {

            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                boolean statusCobro = Boolean.parseBoolean(partes[7]);
                Date fechaCobro = parsearFecha(partes[2], sdf);

                if (fechaCobro != null && fechaCobro.after(fechaInicio) && fechaCobro.before(fechaFin) && statusCobro) {
                    double montoPagado = Double.parseDouble(partes[4]); // Monto que se pagó en esta cuota
                    String idPrestamo = partes[0]; // Identificador del préstamo

                    // Revertir el cobro en el archivo de Préstamo
                    revertirPrestamo(idPrestamo, montoPagado);

                    // Marcar el cobro como no realizado (statusCobro = false)
                    partes[7] = "false";
                    linea = String.join(",", partes);

                    pagosRevertidos++; // Incrementar el contador de pagos revertidos
                }

                bw.write(linea);
                bw.newLine();
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al procesar los cobros: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return 0; // Retornar 0 en caso de error
        }

        // Renombrar archivo temporal
        if (archivoOriginal.delete()) {
            if (!archivoTemporal.renameTo(archivoOriginal)) {
                JOptionPane.showMessageDialog(null, "No se pudo renombrar el archivo temporal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el archivo original.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        return pagosRevertidos; // Retornar la cantidad total de pagos revertidos
    }

    private static void revertirPrestamo(String idPrestamo, double montoPagado) {
        File archivoPrestamosOriginal = new File("Prestamos.txt");
        File archivoPrestamosTemporal = new File("Prestamos.tmp");

        try (BufferedReader br = new BufferedReader(new FileReader(archivoPrestamosOriginal)); BufferedWriter bw = new BufferedWriter(new FileWriter(archivoPrestamosTemporal))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes[0].equals(idPrestamo)) {
                    double balancePrestamo = Double.parseDouble(partes[9]); // Balance actual del préstamo
                    double montoPrestado = Double.parseDouble(partes[8]); // Monto original del préstamo

                    balancePrestamo += montoPagado; // Revertir el pago al balance

                    // Verificar que el balance no exceda el monto prestado
                    if (balancePrestamo > montoPrestado) {
                        balancePrestamo = montoPrestado;
                    }

                      partes[9] = String.format(Locale.US, "%.2f", balancePrestamo); // Actualizar balance

                    if (balancePrestamo > 0) {
                        partes[3] = "true"; // Estado_Prestamo = false si el balance es mayor a cero
                    }

                    linea = String.join(",", partes);
                }
                bw.write(linea);
                bw.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al revertir el archivo de préstamos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Renombrar archivo temporal
        if (archivoPrestamosOriginal.delete()) {
            if (!archivoPrestamosTemporal.renameTo(archivoPrestamosOriginal)) {
                JOptionPane.showMessageDialog(null, "No se pudo renombrar el archivo temporal de préstamos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el archivo original de préstamos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private static Date parsearFecha(String fechaStr, SimpleDateFormat sdf) {
        try {
            return sdf.parse(fechaStr);
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReversarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReversarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReversarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReversarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReversarCobros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReversarCobros;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAnioFinal;
    private javax.swing.JTextField txtAnioInicio;
    private javax.swing.JTextField txtDiaFinal;
    private javax.swing.JTextField txtDiaInicio;
    private javax.swing.JTextField txtMesFinal;
    private javax.swing.JTextField txtMesInicio;
    // End of variables declaration//GEN-END:variables
}
