/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaprestamos;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author erikr
 */
public class MovimientoCobros extends javax.swing.JFrame {

    private DefaultTableModel tblModel;

    /**
     * Creates new form MovimientoCobros
     */
    public MovimientoCobros() {
        initComponents();
        initTableModel();
        setFechaInicioActual();
    }

    private void initTableModel() {
        tblModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{"CUOTA", "FECHA", "MONTO", "ESTADO"}
        );
        jTable1.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCobro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdCteCobro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFechaCobro = new javax.swing.JTextField();
        txtValorCobro = new javax.swing.JTextField();
        btnCobrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("MOVIMIENTO DE COBROS");

        jLabel2.setText("ID COBRO");

        txtIdCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCobroActionPerformed(evt);
            }
        });

        jLabel3.setText("ID CLIENTE");

        txtIdCteCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCteCobroActionPerformed(evt);
            }
        });

        jLabel4.setText("FECHA");

        jLabel5.setText("VALOR COBRO");

        txtFechaCobro.setEditable(false);

        btnCobrar.setText("COBRAR");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        jLabel6.setText("CUOTAS PENDIENTES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CUOTA", "FECHA", "MONTO", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdCteCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addGap(49, 49, 49)
                            .addComponent(txtFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnCobrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdCteCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValorCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCobrar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCobroActionPerformed
        // TODO add your handling code here:
        verificarIdCobro();
    }//GEN-LAST:event_txtIdCobroActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        // TODO add your handling code here:
        // Obtener datos del formulario
        // Verificar que una fila esté seleccionada en la tabla
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una cuota para cobrar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener los datos de la cuota seleccionada
        String cuota = jTable1.getValueAt(selectedRow, 0).toString();
        String fecha = jTable1.getValueAt(selectedRow, 1).toString();
        String monto = jTable1.getValueAt(selectedRow, 2).toString();
        String estado = jTable1.getValueAt(selectedRow, 3).toString();

        // Validar que el monto de cobro es correcto
        String valorCobro = txtValorCobro.getText().trim();
        if (valorCobro.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El valor de cobro no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double montoCuota;
        double valor;
        try {
            montoCuota = Double.parseDouble(monto);
            valor = Double.parseDouble(valorCobro);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor de cobro debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (valor < montoCuota) {
            JOptionPane.showMessageDialog(this, "El valor de cobro no puede ser menor que el monto de la cuota.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Procesar el cobro
        String idCliente = txtIdCteCobro.getText().trim();
        File archivoCuotas = new File("Cuota_Prestamo.txt");
        File archivoCuotasTemp = new File("Cuota_Prestamo_Temp.txt");

        try (BufferedReader reader = new BufferedReader(new FileReader(archivoCuotas)); BufferedWriter writer = new BufferedWriter(new FileWriter(archivoCuotasTemp))) {

            String line;
            boolean cobroRealizado = false;

            while ((line = reader.readLine()) != null) {
                String[] atributos = line.split(",");
                if (atributos[1].equals(idCliente) && atributos[3].equals(cuota) && atributos[7].equals("false")) { // Buscar cuota pendiente
                    // Marcar la cuota como cobrada
                    atributos[7] = "true";
                    cobroRealizado = true;

                    // Actualizar archivo de cobros
                    File archivoCobro = new File("Cobro_Prestamo.txt");
                    try (BufferedWriter cobroWriter = new BufferedWriter(new FileWriter(archivoCobro, true))) {
                        String lineaCobro = txtIdCobro.getText().trim() + "," + idCliente + "," + valorCobro + "," + new SimpleDateFormat("dd/MM/yyyy").format(new Date());
                        cobroWriter.write(lineaCobro);
                        cobroWriter.newLine();
                    }
                }

                // Escribir la línea actualizada en el archivo temporal
                writer.write(String.join(",", atributos));
                writer.newLine();
            }

            if (!cobroRealizado) {
                JOptionPane.showMessageDialog(this, "No se pudo realizar el cobro. Verifique los datos y vuelva a intentarlo.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al procesar el cobro.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        // Reemplazar el archivo original por el archivo temporal
        if (archivoCuotas.delete()) {
            archivoCuotasTemp.renameTo(archivoCuotas);
            JOptionPane.showMessageDialog(this, "Cobro realizado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el archivo de cuotas.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Restar el monto cobrado del balance en Prestamo.txt
        actualizarBalancePrestamo(idCliente, valor);

        // Limpiar campos y actualizar tabla después del cobro
        limpiarCampos();
        buscarCuotasPorCliente();
    }//GEN-LAST:event_btnCobrarActionPerformed
    private void actualizarBalancePrestamo(String idCliente, double montoCobrado) {
        File archivoPrestamos = new File("prestamos.txt");
        File archivoPrestamosTemp = new File("Prestamo_Temp.txt");

        try (BufferedReader reader = new BufferedReader(new FileReader(archivoPrestamos)); BufferedWriter writer = new BufferedWriter(new FileWriter(archivoPrestamosTemp))) {

            String line;
            while ((line = reader.readLine()) != null) {
                String[] atributos = line.split(",");
                if (atributos[1].equals(idCliente)) { // Buscar el préstamo correspondiente al cliente
                    double balanceActual = Double.parseDouble(atributos[9]); // Suponiendo que el balance está en la posición 6
                    double nuevoBalance = balanceActual - montoCobrado;
                    atributos[9] = String.valueOf(nuevoBalance);
                }

                // Escribir la línea actualizada en el archivo temporal
                writer.write(String.join(",", atributos));
                writer.newLine();
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el balance del préstamo.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        // Reemplazar el archivo original por el archivo temporal
        if (archivoPrestamos.delete()) {
            archivoPrestamosTemp.renameTo(archivoPrestamos);
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el archivo de préstamos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtIdCteCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCteCobroActionPerformed
        // TODO add your handling code here:
        buscarCuotasPorCliente();
    }//GEN-LAST:event_txtIdCteCobroActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limpiarCampos() {
        txtIdCobro.setText("");
        txtIdCteCobro.setText("");
        txtValorCobro.setText("");

    }

    private void buscarCuotasPorCliente() {
        String idCliente = txtIdCteCobro.getText().trim();
        File archivoCuotas = new File("Cuota_Prestamo.txt");

        tblModel.setRowCount(0); // Limpiar tabla antes de cargar nuevas cuotas

        try (BufferedReader reader = new BufferedReader(new FileReader(archivoCuotas))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] atributos = line.split(",");
                if (atributos[1].equals(idCliente) && atributos[7].equals("false")) { // Asegurarse de que la cuota esté pendiente
                    tblModel.addRow(new Object[]{
                        atributos[3], // CUOTA
                        atributos[2], // FECHA
                        atributos[4], // MONTO
                        atributos[7] // ESTADO
                    });
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al leer el archivo de cuotas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setFechaInicioActual() {
        // Obtener la fecha actual del sistema
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaActual = dateFormat.format(new Date());
        System.out.println("Fecha actual del sistema: " + fechaActual);

        // Establecer la fecha en el campo de texto
        txtFechaCobro.setText(fechaActual);
    }

    private void verificarIdCobro() {
        String idCobro = txtIdCobro.getText().trim();
        File archivoCobro = new File("Cobro_Prestamo.txt");
        boolean existeCobro = false;

        try (BufferedReader reader = new BufferedReader(new FileReader(archivoCobro))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] atributos = line.split(",");
                if (atributos.length >= 3 && atributos[0].equals(idCobro)) {
                    existeCobro = true;
                    // Aquí deberías mostrar los detalles del cobro
                    JOptionPane.showMessageDialog(this, "Modificando", "Información", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            if (!existeCobro) {
                JOptionPane.showMessageDialog(this, "Creando", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "ERROR", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientoCobros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFechaCobro;
    private javax.swing.JTextField txtIdCobro;
    private javax.swing.JTextField txtIdCteCobro;
    private javax.swing.JTextField txtValorCobro;
    // End of variables declaration//GEN-END:variables
}
